### ISSUE TITLE
Make JRuby 9000 work with Ruboto

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#737]
Hi!

JRuby 9000 (master) currently loads the compiler which uses `java.lang.invoke.MethodHandles` which is not available on Android.

I need help making changes to JRuby master to make loading the compiler optional.

I have started a branch for this here:

https://github.com/jruby/jruby/tree/test-optional_compiler

...but I need help doing the changes, and I need someone to work with for motivation.

Getting this done would be a great boost for the Ruboto project since it has blocked the project for a long while now.

**Comment by donv** [comment]
@headius @enebo I need some guidance on this:  What to exclude, and when.

**Comment by donv** [comment]
I have posted a bounty for this on Bountysource  [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=22760953)](https://www.bountysource.com/issues/22760953-make-jruby-9000-work-with-ruboto?utm_source=22760953&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by miseler** [comment]
It's unclear if the bounty is for what the headline says ("Make JRuby 9000 work with Ruboto") or just for the optional compiler thing, unless You are sure that the optional compiler is the only remaining hurdle.

**Comment by donv** [comment]
Hi @miseler !

Thanks for the interest in the issue!  The bounty is for getting the default app started with JRuby 9K and getting the current test suite green in travis-ci.

**Comment by donv** [comment]
This may help us:  http://www.java2s.com/Code/Jar/j/Downloadjsr292backportjar.htm

**Comment by oneiros** [comment]
I am very interested in this issue. Given the EOL of JRuby 1.7, ruboto is currently in an unfortunate situation. Also, it would be nice to see if 9000 has any performance improvements on Android.

Sadly, not much seems to have happened. I found a number of issues over at the JRuby tracker. I will list them here for reference, as each holds some tiny piece of information that might be useful:

https://github.com/jruby/jruby/issues/2471
https://github.com/jruby/jruby/issues/2982
https://github.com/jruby/jruby/issues/4004

I wish I could be of more help, but given that my Java knowledge is ancient and I have never touched JRuby internals before, I fear there is not much I can do. Still I would love to see some progress.

Let me know, if I can be of any assistance.

**Comment by donv** [comment]
Hi David!

I think the way to JRuby 9K usage is clear.  As I see it, the main work is in JRuby and is Java work.  Java hos not changed much in 20 years, so your ancient knowledge is still valid 😄 .

If you manage to clone the JRuby repository and build a jruby-jars gem, you can contribute, even if only by testing changes done.

I do Ruboto work in my spare time, and I am motivated any contribution by others.

**Comment by oneiros** [comment]
As noted over in https://github.com/jruby/jruby/issues/4004 I have made some progress. I can run (at least some, simple) ruby code on android using a patched version of JRuby 9K.

I can also start a slightly modified¹ ruboto sample app without errors. But now I am stuck :frowning_face: 

While the app starts up fine, it does not display anything, but an empty Activity. Nothing is written to the log either. It looks a lot like, while ruboto clearly tries to call it, the generated ruby class's `onCreate` method is never actually run.

What I do not understand is why this does not result in an Exception or even any output at all. This gives me nothing to work with. I would appreciate any ideas on how to get to the bottom of this.

[¹] I had to use dexmaker in JRuby itself so I needed to remove dx.jar from the generated app. Also, my  version of JRuby seems to require multidex right away, but the fallback did not work for me.

Last but not least: `DalvikProxyClassFactory.java` will currently not work correctly with 9K as the API of the original `ProxyClassFactory` changed recently. I tried a modified version, but without luck. But this should not be causing my troubles, because if it were, it should throw exceptions all over the place.

**Comment by donv** [comment]
Hi @oneiros !
This is very interesting!  Do you have a fork with your changes I could try out?

**Comment by oneiros** [comment]
You can find my patches to JRuby here: https://github.com/oneiros/jruby/tree/android9k

**Comment by oneiros** [comment]
Oh, one more thing: There was already an exception in `JRubyAdapter.java` for JRuby 9K that I had to change. I changed line 226 from

    final String jrubyHome = (jrubyVersion.startsWith("9.0.0.0") ?

to simply

    final String jrubyHome = (jrubyVersion.startsWith("9") ?

as we are well beyond 9.0.0.0 now.

**Comment by donv** [comment]
Got this link from @enebo : http://mail.openjdk.java.net/pipermail/mlvm-dev/2017-March/006750.html

**Comment by donv** [comment]
Restarting this effort now.

**Comment by donv** [comment]
We now have a working guide for JRuby 9.2.  JRuby 9.4 in the works.
