### ISSUE TITLE
can't install ruboto with ruby gems in windows 10.

### ISSUE THREAD

**Issue by leandroruel** [ruboto/ruboto#752]
i'm trying download ruboto with ruby gems in my Windows 10 (i know it sucks) but, when i try install other packages it works fine.

PS C:\Users\leandro> gem install ruboto
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.10.1-x86-mingw32.gemspec.rz)
PS C:\Users\leandro> gem install sass
Fetching: sass-3.4.18.gem (100%)
Successfully installed sass-3.4.18
Parsing documentation for sass-3.4.18
Installing ri documentation for sass-3.4.18
Done installing documentation for sass after 24 seconds
1 gem installed

**Comment by gfowley** [comment]
This...

> ERROR: While executing gem ... (Gem::RemoteFetcher::FetchError)
bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.10.1-x86-mingw32.gemspec.rz)

...indicates a problem with the Pry gem. It references a windows platform gemspec that is missing.

But I don't recall Pry being a Ruboto dependency. Looking at Ruboto dependencies:

 ```
$ gem dependency --remote ruboto --version 1.3.0
Gem ruboto-1.3.0
  main (~> 5.2)
  minitest (~> 5.5, development)
  rake (~> 10.0)
  rubyzip (~> 1.0)

$ gem dependency --remote main --version '~>5.2'
Gem main-5.2.0
  arrayfields (>= 4.7.4)
  chronic (>= 0.6.2)
  fattr (>= 2.2.0)
  map (>= 5.1.0)

Gem main-5.3.1

Gem main-5.3.2
  arrayfields (>= 4.7.4)
  chronic (>= 0.6.2)
  fattr (>= 2.2.0)
  map (>= 5.1.0)
  pry (>= 0.9)
```

Pry is a dependency of gem ```main```, version 5.3.2. The lack of dependencies for version 5.3.1 looks like a packaging error.

I would install gem ```main``` version 5.2.0 to satisfy Ruboto dependencies. That should prevent the problematic later versions being installed, avoiding the Pry windows platform problem.

```
$ gem install main --version '5.2.0'
$ gem install ruboto
```

Hopefully that's the only dependency on Pry. Otherwise you'll need to continue examining the dependencies for workarounds until the Pry gem issue is resolved.  They seem to be aware of it: https://github.com/pry/pry/issues/1436

**Comment by leandroruel** [comment]
thanks! I'll try this.
