### ISSUE TITLE
How can I help? (ChaosCat)

### ISSUE THREAD

**Issue by ChaosCat** [ruboto/ruboto#771]
Hi!

I'd like to contribute to the Ruboto project.

My earlier experience with Ruby, Java, Android and Ruboto:
Four years of programming experience in java, one year of experience in Ruby and three months of android programming experience (with Ruboto).

My experience with HTML, CSS, JavaScript, and Jekyll:
Intermediate level in HTML and CSS, basic knowledge in JavaScript, and almost no experience in Jekyll.

My experience using git and GitHub:
Feeling comfortable using it, contributed to a project before.

My other interests and passions:
I would say game development and graphics in general. I am interested in Ruby and Android, so I wish to contribute to Ruboto and help in ant way I can, I also specifically want to write a set of tutorials for Android development with Ruboto since I am having a hard time finding good learning resources.

**Comment by donv** [comment]
Hi @ChaosCat !

Welcome to the Ruboto project!  We are very happy to have you with us!

I am especially excited that you have already used Ruboto.  Can you tell a bit about what you have done with Ruboto already?

Your ambitions sound just perfect!  Better documentation and learning resources would make our project so much better.

I would like to make your entry into the project as pleasant as possible.  Please tell me if you need anything, and feel free to ask about absolutely anything :smile: 

Since you are thinking about writing tutorials, please take a moment and think about how to write, group, link, publish, and search the tutorials.  We already have contributors who have written tutorials, and I would like for the different contributors to be able to cooperate and work well together.  at the same time, I would like for newcomers like yourself to bring new ideas to the table.

At the moment we have tutorials in the WIKI and @KCErb has written a nice bunch.

https://github.com/ruboto/ruboto/wiki/Tutorials-and-examples
http://kcerb.com/hello-ruboto/

I am thinking maybe the Ruboto GitHub pages using jekyll are the best place to write this, but I have no strong opinions on how or where to write and publish the tutorials.  I just want it to be easy to contribute, and that different contributors have an easy way to cooperate.

Maybe you can open an issue in the tracker for discussing this?

**Comment by ChaosCat** [comment]
I used ruboto mostly through my Android device, the experience was really fine and I was excited about the idea of using my phone for testing, but there were a few points that I found unpleasant (*by my experience with ruboto on my pc is way better but AI

*   too many script errors and a lot of pretty fundamental functions weren't supported such as the '.chomp' and the 'range()' methods/classes, also a lot of (or rather most) of the demos are broken.
* the text editor was really difficult to work with and there was no text highlighting

**Comment by donv** [comment]
Hi @ChaosCat !

These are really good insights.  We love hearing real-world stories of using Ruboto.

Ruboto uses JRuby 1.7.x which means it supports Ruby 1.9.3 syntax and libraries.  #chomp and range methods present in Ruby 1.9.3 should all be available.  If not, that is a good issue to open in the tracker.

Which text editor did you use?  The one built into Ruboto-IRB or the web editor, or something else?

**Comment by ChaosCat** [comment]
I am using the Ruboto IRB built in editor, the (Android Ruboto IRB) console doesn't accept any sort of input. it also says that the object class itself does not support such method as 'range' and 'chomp', I will open an issue regarding the input problem.

In other news, I started using Jekyll and got the hang of it, so I think I can help now with it too.

**Comment by donv** [comment]
Nice @ChaosCat !

Looking forward to your issues and contributions :smile: 

Welcome to the project!
