### ISSUE TITLE
Ruboto 1.5.0 project with flag --with-jruby still asks for Ruboto Core installation

### ISSUE THREAD

**Issue by loloof64** [ruboto/ruboto#823]
Hello,

I've just generated an application with the following command

    $ ruboto gen app --package com.loloof64.ruboto.simple_chess_board --name SimpleChessBoard --target android-15 --with-jruby 1.7.26

but when I launch `rake install start` the application still asks for a Ruboto Core installation.

My OS is Ubuntu Gnome 16.10 64 bit, and I successfully setup the ruboto core.

**Comment by monochrome-particles** [comment]
Hi there,
What version of android sdk and build tools are you using?
Is it that after you install and start the app on your device, you get the screen saying "Get Ruboto Core" with a link to Google Play store?
If so, I ran into similar problems in the past, and I got it fixed by simply using build tools 23.0.0.

Source: https://github.com/ruboto/ruboto/issues/809

**Comment by loloof64** [comment]
Hello, thanks for your answer. It's been quite ago since I've been trying Ruboto for the last time. But my environment is the same.

I was using Android SDK tools 25.2.3 and I am upgrading it to 25.2.4. And also Android SDK Platform Tools 25.0.1 which I am upgrading to 25.0.3. And also using an x86 emulator (api 23).

I will retry with my already generated project as soon as my update is complete.

**Comment by loloof64** [comment]
Yes you're right :)

Simply updating the Android SDK solves the problem.

Thank you again :)
