### ISSUE TITLE
`` seems to be the same thing as " and ' and system never returns a value

### ISSUE THREAD

**Issue by thomasjslone** [ruboto/ruboto#833]
what if i need to get the shell response, where do terminal/system calls go in android... no ones talking about it on google so im here, i just wanna see ls /mnt/sdcard return my list of stuff

**Comment by donv** [comment]
Hi @thomasjslone !

Did you figure this out?

**Comment by MaxPleaner** [comment]
@donv in the interest of preventing this repo's issues page from having too many open issues, I think stuff like this should be closed and the poster should be advised to try stackoverflow. The "how can I help" stuff should also be closed, in my opinion, because they are not actually open issues at all.

**Comment by donv** [comment]
Closing obsolete issue.
